import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { DesignResult } from '@/lib/types'
import type { ProjectMeta } from '@/store/project'
import { fmt } from '@/lib/format'

export interface ReportResult {
  title: string
  result: DesignResult
}

export interface ReportOptions {
  meta: ProjectMeta
  overview: [string, string][]
  results: ReportResult[]
}

function finalY(doc: jsPDF): number {
  return (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY
}

function sanitize(s: string): string {
  return s.replace(/[^a-z0-9\-_]+/gi, '_').slice(0, 40) || 'project'
}

export function exportProjectPDF(opts: ReportOptions) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const margin = 40

  doc.setFillColor(11, 18, 32)
  doc.rect(0, 0, pageW, 70, 'F')
  doc.setFillColor(244, 180, 0)
  doc.rect(0, 70, pageW, 3, 'F')
  doc.setTextColor(244, 180, 0)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text('PaveWorks — Pavement Design Report', margin, 34)
  doc.setTextColor(200, 210, 225)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(`${opts.meta.name}   ·   ${opts.meta.location || '—'}   ·   ${opts.meta.date}`, margin, 52)

  autoTable(doc, {
    startY: 92,
    head: [['Parameter', 'Value']],
    body: opts.overview,
    theme: 'grid',
    headStyles: { fillColor: [30, 41, 59] },
    styles: { fontSize: 9, cellPadding: 4 },
    margin: { left: margin, right: margin },
  })
  let y = finalY(doc) + 18

  for (const r of opts.results) {
    if (y > pageH - 120) {
      doc.addPage()
      y = 50
    }
    doc.setTextColor(20, 30, 50)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.text(`${r.title}: ${r.result.sectionLabel}  [${r.result.ok ? 'OK' : 'REVISE'}]`, margin, y)

    const summaryRows = Object.entries(r.result.summary).map(([k, v]) => [k, typeof v === 'number' ? fmt(v) : String(v)])
    autoTable(doc, {
      startY: y + 8,
      head: [['Result', 'Value']],
      body: summaryRows,
      theme: 'striped',
      headStyles: { fillColor: [30, 41, 59] },
      styles: { fontSize: 9, cellPadding: 3 },
      margin: { left: margin, right: margin },
    })
    y = finalY(doc) + 8

    if (r.result.checks.length) {
      const checkRows = r.result.checks.map((c) => [
        c.label,
        `${fmt(c.value)}${c.limit !== undefined ? ` / ${fmt(c.limit)}` : ''}${c.unit ? ` ${c.unit}` : ''}`,
        c.status.toUpperCase(),
      ])
      autoTable(doc, {
        startY: y,
        head: [['Check', 'Value / Limit', 'Status']],
        body: checkRows,
        theme: 'grid',
        headStyles: { fillColor: [30, 41, 59] },
        styles: { fontSize: 8.5, cellPadding: 3 },
        margin: { left: margin, right: margin },
      })
      y = finalY(doc) + 16
    } else {
      y += 8
    }
  }

  const pages = doc.getNumberOfPages()
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i)
    doc.setFontSize(7.5)
    doc.setTextColor(120, 130, 145)
    doc.text(
      'Generated by PaveWorks. Indicative — verify against the governing standard (DoR / ORN 31 / IRC / AASHTO) before construction.',
      margin,
      pageH - 22,
    )
    doc.text(`Page ${i} / ${pages}`, pageW - margin - 48, pageH - 22)
  }

  doc.save(`${sanitize(opts.meta.name)}-pavement-report.pdf`)
}
